# Sample pipeline 

trigger:
- master

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'

steps:
# build the solution 
- script: dotnet build ./Milestone4 --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

